name: Deploy FastAPI to Cloud Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and setuptools
        run: python -m pip install --upgrade pip setuptools

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check for broken dependencies
        run: pip check

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: lik-460814

      - name: Enable required APIs
        run: |
          gcloud services enable run.googleapis.com
          gcloud services enable cloudbuild.googleapis.com

      - name: Deploy to Cloud Run (dev)
        run: |
          gcloud config unset auth/credential_file_override
          gcloud run deploy weathernews-dev \
            --source=. \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --port=8000 \
            --memory=1Gi \
            --cpu=1 \
            --max-instances=10 \
            --quiet

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: lik-460814

      - name: Deploy to Cloud Run (prod)
        run: |
          gcloud config unset auth/credential_file_override
          gcloud run deploy weathernews-prod \
            --source=. \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --port=8000 \
            --memory=1Gi \
            --cpu=1 \
            --max-instances=20 \
            --quiet