name: Deploy Flask API to Cloud Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and setuptools
        run: python -m pip install --upgrade pip setuptools

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check for broken dependencies
        run: pip check

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: novi-464614

      - name: Deploy to Cloud Run (dev)
        run: |
          gcloud config unset auth/credential_file_override
          gcloud run deploy weathernews-dev \
            --source=. \
            --region=europe-west1 \
            --platform=managed \
            --allow-unauthenticated \
            --quiet
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_SEARCH_API_KEY: ${{ secrets.GOOGLE_SEARCH_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}

  approval:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://weathernews-prod-europe-west1.a.run.app

    steps:
      - name: Await manual approval
        run: echo "Waiting for production deployment approval..."

  deploy-prod:
    needs: approval
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: novi-464614

      - name: Deploy to Cloud Run (prod)
        run: |
          gcloud config unset auth/credential_file_override
          gcloud run deploy weathernews-prod \
            --source=. \
            --region=europe-west1 \
            --platform=managed \
            --allow-unauthenticated \
            --quiet
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_SEARCH_API_KEY: ${{ secrets.GOOGLE_SEARCH_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
