name: Deploy FastAPI to Cloud Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build & Install Dependencies
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and setuptools
        run: python -m pip install --upgrade pip setuptools

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check for broken dependencies
        run: pip check

  deploy-dev:
    name: Deploy to Cloud Run (Dev)
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: cvoapi
          export_default_credentials: true

      - name: Deploy to Cloud Run (Dev)
        run: |
          gcloud run deploy weathernews-dev \
            --source=. \
            --project=cvoapi \
            --region=asia-south1 \
            --platform=managed \
            --allow-unauthenticated \
            --memory=1Gi \
            --cpu=1 \
            --max-instances=10 \
            --set-env-vars="SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_KEY=${{ secrets.SUPABASE_KEY }},GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GOOGLE_SEARCH_API_KEY=${{ secrets.GOOGLE_SEARCH_API_KEY }},GOOGLE_CSE_ID=${{ secrets.GOOGLE_CSE_ID }}" \
            --quiet

  deploy-prod:
    name: Deploy to Cloud Run (Prod)
    needs: deploy-dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: cvoapi
          export_default_credentials: true

      - name: Deploy to Cloud Run (Prod)
        run: |
          gcloud config unset auth/credential_file_override
          gcloud run deploy weathernews-prod \
            --source=. \
            --project=cvoapi \
            --region=asia-south1 \
            --platform=managed \
            --allow-unauthenticated \
            --memory=1Gi \
            --cpu=1 \
            --max-instances=20 \
            --set-env-vars="GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GOOGLE_SEARCH_API_KEY=${{ secrets.GOOGLE_SEARCH_API_KEY }},GOOGLE_CSE_ID=${{ secrets.GOOGLE_CSE_ID }},SUPABASE_KEY=${{ secrets.SUPABASE_KEY }},SUPABASE_URL=${{ secrets.SUPABASE_URL }}" \
            --quiet
